ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS formula character varying(2000) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS taxable_formula character varying(2000) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS exempt_formula character varying(2000) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS imss_taxable_formula character varying(2000) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS sat_tipo_percepcion_code character varying(20) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS sat_tipo_deduccion_code character varying(20) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS sat_tipo_otro_pago_code character varying(20) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS sat_agrupador character varying(40) NOT NULL DEFAULT '';
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS automatic_on_global_run boolean NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS automatic_on_termination boolean NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS is_in_kind boolean NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS affects_seventh_day boolean NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS affects_holiday_pay boolean NOT NULL DEFAULT false;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS affects_imss boolean NOT NULL DEFAULT true;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS affects_isr boolean NOT NULL DEFAULT true;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS affects_accumulators boolean NOT NULL DEFAULT true;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS requires_sat_stamping boolean NOT NULL DEFAULT true;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS min_amount numeric(18,2) NOT NULL DEFAULT 0;
ALTER TABLE IF EXISTS payroll.payroll_concepts ADD COLUMN IF NOT EXISTS max_amount numeric(18,2) NOT NULL DEFAULT 0;
