-- One-time migration to move existing public tables into modular schemas without losing data.
-- Run this before launching the app against an existing database that already has data in public.
BEGIN;
CREATE SCHEMA IF NOT EXISTS "accounting";
CREATE SCHEMA IF NOT EXISTS "auth";
CREATE SCHEMA IF NOT EXISTS "catalog";
CREATE SCHEMA IF NOT EXISTS "config";
CREATE SCHEMA IF NOT EXISTS "core";
CREATE SCHEMA IF NOT EXISTS "finance";
CREATE SCHEMA IF NOT EXISTS "hr";
CREATE SCHEMA IF NOT EXISTS "inventory";
CREATE SCHEMA IF NOT EXISTS "org";
CREATE SCHEMA IF NOT EXISTS "payroll";
CREATE SCHEMA IF NOT EXISTS "product";
CREATE SCHEMA IF NOT EXISTS "purchase";
CREATE SCHEMA IF NOT EXISTS "sales";
CREATE SCHEMA IF NOT EXISTS "subscription";
ALTER TABLE IF EXISTS public."tenants" SET SCHEMA "core";
ALTER TABLE IF EXISTS public."Plans" SET SCHEMA "subscription";
ALTER TABLE IF EXISTS "subscription"."Plans" RENAME TO "plans";
ALTER TABLE IF EXISTS public."companies" SET SCHEMA "core";
ALTER TABLE IF EXISTS public."branches" SET SCHEMA "core";
ALTER TABLE IF EXISTS public."warehouses" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."users" SET SCHEMA "auth";
ALTER TABLE IF EXISTS public."roles" SET SCHEMA "auth";
ALTER TABLE IF EXISTS public."permissions" SET SCHEMA "auth";
ALTER TABLE IF EXISTS public."user_roles" SET SCHEMA "auth";
ALTER TABLE IF EXISTS public."role_permissions" SET SCHEMA "auth";
ALTER TABLE IF EXISTS public."user_sessions" SET SCHEMA "auth";
ALTER TABLE IF EXISTS public."AccessLogs" SET SCHEMA "auth";
ALTER TABLE IF EXISTS "auth"."AccessLogs" RENAME TO "access_logs";
ALTER TABLE IF EXISTS public."navigation_items" SET SCHEMA "core";
ALTER TABLE IF EXISTS public."AuditLogs" SET SCHEMA "core";
ALTER TABLE IF EXISTS "core"."AuditLogs" RENAME TO "audit_logs";
ALTER TABLE IF EXISTS public."ErrorLogs" SET SCHEMA "core";
ALTER TABLE IF EXISTS "core"."ErrorLogs" RENAME TO "error_logs";
ALTER TABLE IF EXISTS public."currencies" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."exchange_rates" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."taxes" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."units" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."banks" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."countries" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."states" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."cities" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."document_series" SET SCHEMA "core";
ALTER TABLE IF EXISTS public."document_folios" SET SCHEMA "core";
ALTER TABLE IF EXISTS public."company_settings" SET SCHEMA "config";
ALTER TABLE IF EXISTS public."customers" SET SCHEMA "org";
ALTER TABLE IF EXISTS public."suppliers" SET SCHEMA "org";
ALTER TABLE IF EXISTS public."third_party_contacts" SET SCHEMA "org";
ALTER TABLE IF EXISTS public."third_party_addresses" SET SCHEMA "org";
ALTER TABLE IF EXISTS public."third_party_bank_accounts" SET SCHEMA "org";
ALTER TABLE IF EXISTS public."item_categories" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."item_brands" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."item_models" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."items" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."item_price_lists" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."item_price_list_details" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."item_barcodes" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."unit_conversions" SET SCHEMA "catalog";
ALTER TABLE IF EXISTS public."product_size_runs" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_size_run_sizes" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_families" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_lasts" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_lines" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_styles" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."embroidery_patterns" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."item_engineering_profiles" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."material_families" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."material_subfamilies" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."material_items" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."finished_products" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_components" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."finished_product_materials" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_consumption_profiles" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_technical_sheets" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_technical_sheet_materials" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_technical_sheet_processes" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_cost_sheets" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_authorization_records" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."product_size_consumption_variations" SET SCHEMA "product";
ALTER TABLE IF EXISTS public."hr_departments" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_positions" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_employees" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."employee_contracts" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_employee_incidents" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."payroll_periods" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_concepts" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_runs" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_run_lines" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_run_line_details" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."hr_attendance_punches" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."payroll_recurring_movements" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."employee_loans" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."employee_loan_deductions" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."hr_work_shifts" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_work_schedules" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_time_clock_devices" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_leave_types" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_vacation_requests" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_employee_documents" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_employee_movements" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_employee_certifications" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_recruitment_vacancies" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_candidate_applications" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_onboarding_checklists" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_employee_performance_reviews" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_employee_competency_assessments" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."hr_succession_plan_records" SET SCHEMA "hr";
ALTER TABLE IF EXISTS public."payroll_attendance_daily_summaries" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_prepayroll_adjustments" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_prepayroll_cutoffs" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_source_applications" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_receipt_controls" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_run_closings" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_dispersion_batches" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_dispersion_lines" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_accounting_postings" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_tax_accumulators" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_employer_obligations" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."payroll_fiscal_reconciliations" SET SCHEMA "payroll";
ALTER TABLE IF EXISTS public."purchase_requisitions" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_requisition_lines" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_orders" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_order_lines" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_receipts" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_receipt_lines" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_invoices" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_invoice_lines" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_returns" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."purchase_return_lines" SET SCHEMA "purchase";
ALTER TABLE IF EXISTS public."stock_balances" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_movements" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_entries" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_entry_lines" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_exits" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_exit_lines" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_transfers" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_transfer_lines" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_adjustments" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."inventory_adjustment_lines" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."physical_counts" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."physical_count_lines" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."item_lots" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."item_serials" SET SCHEMA "inventory";
ALTER TABLE IF EXISTS public."sales_quotes" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_quote_lines" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_orders" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_order_lines" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_shipments" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_shipment_lines" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_invoices" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_invoice_lines" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_returns" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."sales_return_lines" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."credit_notes" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."credit_note_lines" SET SCHEMA "sales";
ALTER TABLE IF EXISTS public."cash_accounts" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."bank_accounts" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."cash_movements" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."bank_movements" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."treasury_incomes" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."treasury_income_lines" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."treasury_expenses" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."treasury_expense_lines" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."receipts" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."receipt_lines" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."payments" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."payment_lines" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."reconciliations" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."reconciliation_lines" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."accounts_receivable_accounts" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."accounts_receivable_movements" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."receipt_applications" SET SCHEMA "finance";
ALTER TABLE IF EXISTS public."accounting_accounts" SET SCHEMA "accounting";
ALTER TABLE IF EXISTS public."accounting_fiscal_periods" SET SCHEMA "accounting";
ALTER TABLE IF EXISTS public."accounting_journal_entries" SET SCHEMA "accounting";
ALTER TABLE IF EXISTS public."accounting_journal_entry_lines" SET SCHEMA "accounting";
ALTER TABLE IF EXISTS public."accounting_ledger_snapshots" SET SCHEMA "accounting";
COMMIT;