namespace Nanchesoft.Web.Services.Products;

public sealed record ProductTechnicalSheetRequest(
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductStyleId,
    string SheetCode,
    string SheetName,
    string Status,
    string ProductDisplayName,
    string PhotoUrl,
    string MainMaterialName,
    string MainColorName,
    string SizeRunCode,
    string Notes,
    bool IsApproved,
    DateTime? ApprovedAtUtc,
    string ApprovedBy,
    bool IsActive,
    string? UpdatedBy,
    List<ProductTechnicalSheetMaterialRequest> Materials,
    List<ProductTechnicalSheetProcessRequest> Processes);

public sealed record ProductTechnicalSheetMaterialRequest(
    Guid MaterialItemId,
    string ComponentCode,
    string ComponentName,
    string MaterialCode,
    string MaterialName,
    string UnitCode,
    decimal Quantity,
    decimal WastePercent,
    int SortOrder,
    bool ShowOnTechnicalSheet,
    string Notes);

public sealed record ProductTechnicalSheetProcessRequest(
    string ProcessCode,
    string ProcessName,
    string WorkstationCode,
    string DeliverToWarehouseCode,
    bool RequiresVoucherCard,
    bool ShowMaterialsOnVoucher,
    int SortOrder,
    string Notes);

public sealed record ProductTechnicalSheetDto(
    Guid Id,
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductStyleId,
    string SheetCode,
    string SheetName,
    string Status,
    string ProductDisplayName,
    string PhotoUrl,
    string MainMaterialName,
    string MainColorName,
    string SizeRunCode,
    string Notes,
    bool IsApproved,
    DateTime? ApprovedAtUtc,
    string ApprovedBy,
    bool IsActive,
    DateTime CreatedAt,
    string? CreatedBy,
    DateTime? UpdatedAt,
    string? UpdatedBy,
    List<ProductTechnicalSheetMaterialDto> Materials,
    List<ProductTechnicalSheetProcessDto> Processes);

public sealed record ProductTechnicalSheetMaterialDto(
    Guid Id,
    Guid MaterialItemId,
    string ComponentCode,
    string ComponentName,
    string MaterialCode,
    string MaterialName,
    string UnitCode,
    decimal Quantity,
    decimal WastePercent,
    int SortOrder,
    bool ShowOnTechnicalSheet,
    string Notes);

public sealed record ProductTechnicalSheetProcessDto(
    Guid Id,
    string ProcessCode,
    string ProcessName,
    string WorkstationCode,
    string DeliverToWarehouseCode,
    bool RequiresVoucherCard,
    bool ShowMaterialsOnVoucher,
    int SortOrder,
    string Notes);

public sealed record ProductCostSheetRequest(
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductTechnicalSheetId,
    string CostSheetCode,
    string Status,
    decimal DirectMaterialCost,
    decimal DirectLaborCost,
    decimal IndirectManufacturingCost,
    decimal PackagingCost,
    decimal ServiceCost,
    decimal TotalCost,
    decimal TargetMarginPercent,
    decimal SuggestedSalePrice,
    string CurrencyCode,
    string Notes,
    bool IsApproved,
    DateTime? ApprovedAtUtc,
    string ApprovedBy,
    bool IsActive,
    string? UpdatedBy);

public sealed record ProductCostSheetDto(
    Guid Id,
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductTechnicalSheetId,
    string CostSheetCode,
    string Status,
    decimal DirectMaterialCost,
    decimal DirectLaborCost,
    decimal IndirectManufacturingCost,
    decimal PackagingCost,
    decimal ServiceCost,
    decimal TotalCost,
    decimal TargetMarginPercent,
    decimal SuggestedSalePrice,
    string CurrencyCode,
    string Notes,
    bool IsApproved,
    DateTime? ApprovedAtUtc,
    string ApprovedBy,
    bool IsActive,
    DateTime CreatedAt,
    string? CreatedBy,
    DateTime? UpdatedAt,
    string? UpdatedBy);

public sealed record ProductAuthorizationRecordRequest(
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductTechnicalSheetId,
    Guid? ProductCostSheetId,
    string AuthorizationCode,
    string Status,
    bool RequiresPhoto,
    bool RequiresConsumption,
    bool RequiresMaterialAssignment,
    bool RequiresCostSheet,
    bool HasPhoto,
    bool HasConsumption,
    bool HasMaterialAssignment,
    bool HasCostSheet,
    DateTime? AuthorizedAtUtc,
    string AuthorizedBy,
    string RejectionReason,
    string Notes,
    bool IsActive,
    string? UpdatedBy);

public sealed record ProductAuthorizationRecordDto(
    Guid Id,
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductTechnicalSheetId,
    Guid? ProductCostSheetId,
    string AuthorizationCode,
    string Status,
    bool RequiresPhoto,
    bool RequiresConsumption,
    bool RequiresMaterialAssignment,
    bool RequiresCostSheet,
    bool HasPhoto,
    bool HasConsumption,
    bool HasMaterialAssignment,
    bool HasCostSheet,
    DateTime? AuthorizedAtUtc,
    string AuthorizedBy,
    string RejectionReason,
    string Notes,
    bool IsActive,
    DateTime CreatedAt,
    string? CreatedBy,
    DateTime? UpdatedAt,
    string? UpdatedBy);

public sealed record ProductSizeConsumptionVariationRequest(
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductComponentId,
    string BaseSizeCode,
    string TargetSizeCode,
    decimal VariationPercent,
    decimal QuantityDelta,
    bool AppliesToConsumption,
    bool AppliesToCosting,
    string Notes,
    bool IsActive,
    string? UpdatedBy);

public sealed record ProductSizeConsumptionVariationDto(
    Guid Id,
    Guid TenantId,
    Guid CompanyId,
    Guid FinishedProductId,
    Guid? ProductComponentId,
    string BaseSizeCode,
    string TargetSizeCode,
    decimal VariationPercent,
    decimal QuantityDelta,
    bool AppliesToConsumption,
    bool AppliesToCosting,
    string Notes,
    bool IsActive,
    DateTime CreatedAt,
    string? CreatedBy,
    DateTime? UpdatedAt,
    string? UpdatedBy);


public sealed record ProductTechnicalCenterRowDto(
    Guid FinishedProductId,
    Guid TenantId,
    Guid CompanyId,
    string ProductCode,
    string ProductName,
    string ProductStyleName,
    string SizeRunName,
    string MainMaterialName,
    bool HasPhoto,
    bool HasConsumption,
    bool HasMaterialAssignments,
    bool HasTechnicalSheet,
    bool HasApprovedTechnicalSheet,
    bool HasCostSheet,
    bool HasApprovedCostSheet,
    bool IsAuthorizedForExplosion,
    string AuthorizationStatus,
    string TechnicalSheetCode,
    string CostSheetCode,
    string AuthorizationCode,
    int MaterialAssignmentCount,
    int ConsumptionProfileCount,
    decimal TotalCost,
    decimal SuggestedSalePrice,
    int ReadinessPercent,
    string PrincipalBlocker,
    string MissingItems);

public sealed record ProductTechnicalActionResponse(
    Guid FinishedProductId,
    string ProductCode,
    string ProductName,
    string Action,
    string Status,
    string Message,
    bool IsAuthorizedForExplosion,
    int ReadinessPercent,
    string PrincipalBlocker);
